export const GET_LISTS_REQUEST = 'GET_LISTS_REQUEST';
export const GET_LISTS_SUCCESS = 'GET_LISTS_SUCCESS';
export const GET_LISTS_FAILURE = 'GET_LISTS_FAILURE';

export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAILURE = 'POST_LIST_FAILURE';

export const PUT_LIST_REQUEST = 'PUT_LIST_REQUEST';
export const PUT_LIST_SUCCESS = 'PUT_LIST_SUCCESS';
export const PUT_LIST_FAILURE = 'PUT_LIST_FAILURE';

export const DELETE_LIST_REQUEST = 'DELETE_LIST_REQUEST';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const DELETE_LIST_FAILURE = 'DELETE_LIST_FAILURE';

export const POST_TODO_REQUEST = 'POST_TODO_REQUEST';
export const POST_TODO_SUCCESS = 'POST_TODO_SUCCESS';
export const POST_TODO_FAILURE = 'POST_TODO_FAILURE';

export const PUT_TODO_REQUEST = 'PUT_TODO_REQUEST';
export const PUT_TODO_SUCCESS = 'PUT_TODO_SUCCESS';
export const PUT_TODO_FAILURE = 'PUT_TODO_FAILURE';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';


export const CHANGE_STATUS_REQUEST = 'CHANGE_STATUS_REQUEST'; 
export const CHANGE_STATUS_SUCCESS = 'CHANGE_STATUS_SUCCESS';
export const CHANGE_STATUS_FAILURE = 'CHANGE_STATUS_FAILURE';